[build]
  # Vite 빌드 명령어
  command = "npm run build"
  # Vite가 결과물을 뱉는 폴더명 (보통 dist)
  publish = "dist"

# [중요] 프록시 설정
[[redirects]]
  from = "/api/tronscan/*"
  to = "https://apilist.tronscanapi.com/:splat"
  status = 200
  force = true

# [중요] SPA 라우팅 (새로고침 시 404 방지)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200